#!/usr/bin/env python

from optparse import OptionParser
from i3ipc import *
import i3ipc
from time import sleep
from os import environ

parser = OptionParser()
parser.add_option("-i", "--socket", dest="ipcfile", help="Set IPC socket location. [default: %s]" % (I3_IPCFILE,))
parser.add_option("-s", "--send", dest="command", help="Send command to window manager.")
parser.add_option("-S", "--subscribe", dest="subscription", help="Print specified window manager events to STDOUT.")
parser.add_option("-W", "--get-workspace", dest="workspace", help="Get a named or indexed workspace information.")
parser.add_option("-w", "--get-workspaces", dest="workspaces", action="store_true", help="Get workspace information.")
parser.add_option("-o", "--get-outputs", dest="outputs", action="store_true", help="Get available RandR outputs.")
(options, args) = parser.parse_args()

if __name__ == '__main__':
    ipcfile = options.ipcfile if options.ipcfile else I3_IPCFILE

    if options.subscription:
        def listener(caller, data):
            #print(data['payload'])
            msg = 'TYPE: {}\n'\
                  'PAYLOAD: {}\n'\
                  'EVENT_PAYLOAD: {}\n'\
                  .format(data['type'],
                          data['payload'],
                          data['event_payload'])
            print(msg)

        if ',' in options.subscription:
            subscriptions = options.subscription.split(',')
            event_type = getattr(i3ipc, subscriptions[0])
            event_other = subscriptions[1] if len(subscriptions) > 1 else ''
        else:
            event_type = getattr(i3ipc, options.subscription)
            event_other = ''

        event = I3EventListener(listener, event_type, event_other, ipcfile)
        try:
            while event.is_alive():
                sleep(1)
        except KeyboardInterrupt:
            event.unsubscribe()

    else:
        socket = I3Socket(ipcfile)

        if options.command:
            print(socket.send_command(options.command)['payload'])

        if options.workspace:
            workspaces = socket.get_workspaces()['payload']
            for workspace in workspaces:
                if workspace['name'].endswith(': ' + options.workspace) or\
                workspace['name'].startswith(options.workspace):
                    print(workspace)
        elif options.workspaces:
            print(socket.get_workspaces()['payload'])
        elif options.outputs:
            print(socket.get_outputs()['payload'])
